### ISSUE TITLE
Compilation fails on Manjaro Linux

### ISSUE THREAD

**Issue by bl0x** [flueke/mesytec-mvlc#1] opened 2021-07-15 10:10 UTC
gcc -dumpversion
  11.1.0
uname -a
  Linux krnbg007 5.10.42-1-MANJARO #1 SMP PREEMPT Thu Jun 3 14:37:11 UTC 2021 x86_64 GNU/Linux

error message:

[ 58%] Building CXX object src/mesytec-mvlc/CMakeFiles/mesytec-mvlc.dir/mvlc_replay.cc.o
mesytec-mvlc/src/mesytec-mvlc/mvlc_replay.cc: In Elementfunktion »void mesytec::mvlc::ReplayWorker::Private::loop(std::promise<std::error_code>)«:
mesytec-mvlc/src/mesytec-mvlc/mvlc_replay.cc:342:35: Fehler:  sleep_for« ist kein Element von »std::this_thread«
  342 |                 std::this_thread::sleep_for(PauseSleepDuration);
      |                                   ^~~~~~~~~
make[2]: *** [src/mesytec-mvlc/CMakeFiles/mesytec-mvlc.dir/build.make:342: src/mesytec-mvlc/CMakeFiles/mesytec-mvlc.dir/mvlc_replay.cc.o] Fehler

**Comment by flueke** [comment] 2021-07-19 12:31
Was able to reproduce this today. It's weird as sleep_for() is in the standard since c++11 and I've not seen this error
on any other distribution/platform. This might be caused by linking in the static version of libstdc++ which comes bundled
with the FTDI D3XX driver and which might override the system libstdc++. I'm currently now sure how to fix this or track it down.

**Comment by op3** [comment] 2021-07-22 11:33
I had the same problem on Arch Linux. I was able to fix it by adding `#include <thread>` to `mvlc_replay.cc`.

**Comment by flueke** [comment] 2021-08-05 13:47
Should be fixed in 574feb8d0e784087df916f1488ad34d2748bd54a

Thank you op3!

**Closed by flueke** 2021-08-05 13:47 UTC
